Models/Quotes.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace QuotingDojo.Models
{
  public class Quote
  {
    [Required]
    [MinLength(3)]
    [Display(Name="Author:")]
    public string Author { get; set; }

    [Required]
    [MinLength(5)]
    [Display(Name="Quotes:")]
    public string Content { get; set; }
  }
}

Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using QuotingDojo.Models;
using DbConnection;

namespace QuotingDojo.Controllers
{
  public class QuoteController : Controller
  {
    [HttpGet("")]
    public IActionResult Index()
    {
      return View();
    }

    [HttpGet("quotes")]
    public IActionResult Show()
    {
      List<Dictionary<string, object>> Quotes = DbConnector.Query("SELECT * FROM quotes ORDER BY created_at DESC");
      return View("Quotes", Quotes);
    }

    [HttpPost("quotes")]
    public IActionResult Create(Quote quote)
    {
      if(ModelState.IsValid)
      {
        string query = $"INSERT INTO quotes (author, quote) VALUES ('{quote.Author}', '{quote.Content}')";
        DbConnector.Execute(query);
        System.Console.WriteLine("valid quote");
        System.Console.WriteLine(quote.Author);
        System.Console.WriteLine(quote.Content);
        return RedirectToAction("Show");
      }
      else 
      {
        System.Console.WriteLine(quote.Author);
        System.Console.WriteLine(quote.Content);
        System.Console.WriteLine("invalid quote");
        return View("Index"); 
      }
    }

  }
}

Views/Quote/Index.cshtml
@model Quote

<div class="container-fluid">
  <div class="row">
    <h1>Welcome to Quoting Dojo</h1>
    <div class="col-md-12">
      <form asp-action="Create" asp-controller="Quote" method="post">
        <div class="form-group">
          <span asp-validation-for="Author" class="text-danger"></span>
          <label asp-for="Author" class="form-horizontal" style="display: inline-block"></label>
          <input asp-for="Author" class="form-horizontal" class="form-control">
        </div>
        <div class="form-group">
          <span asp-validation-for="Content" class="text-danger"></span>
          <label asp-for="Content" class="form-horizontal"  style="display: inline-block; vertical-align: top;"></label>
          <textarea asp-for="Content" id="plan" cols="30" rows="10"></textarea>
        </div>
        <!-- <input class="submit" type="submit" value="Submit!"> -->
        <button class="btn btn-primary">Submit!</button>
      </form>
    </div>
  </div>
</div>

Views/Quote/Quotes.cshtml
@model List<Dictionary<string, object>>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      @{
        foreach(var quote in Model)
        {
          <p class="text-primary">"@quote["quote"]"</p>
          <p class="text-primary">@quote["author"] @quote["created_at"]</p>
          <hr>
        }
      }
    </div>
  </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>QuotingDojo</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

</body>
</html>